add first version TokenLocker
starcoinorg/starcoin-framework-commons pull request #43
Opened 2022-07-28 07:26 UTC by YusongWang

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

impl TokenLocker

Issue Number: #32

## What is the new behavior?

- 允许用户锁定多种token,锁定多次。

## Other information

2022-07-28 07:48 UTC, jiangying000 commented
Maybe add some unit tests ?

2022-07-28 15:07 UTC, 0xpause requested changes

2022-07-28 15:07 UTC, 0xpause commented on sources/TokenLocker.move
> +                    Account::deposit_to_self<TokenT>(sender, t);
既然 lock 是传入的 Token，那这里最好也将 Token 返回，保持形式对应。

可以增加两个接口用户从自己账号下面锁定和解锁Token：
public fun lock_self<TokenT: store>(sender: &signer, amout: u128, unlock_time: u64)
public fun unlock_self<TokenT: store>(sender: &signer)

2022-07-29 02:24 UTC, YusongWang commented on sources/TokenLocker.move
> +                    Account::deposit_to_self<TokenT>(sender, t);
已经添加了

2022-07-29 02:24 UTC, YusongWang commented on sources/TokenLocker.move
> +            //let _locker = borrow_global<TokenLocker<TokenT>>(addresses);
ok

2022-07-29 02:24 UTC, YusongWang commented on sources/TokenLocker.move
> +    public fun lock<TokenT:store>(sender:&signer,t:Token<TokenT>,timestamp:u64) acquires TokenLocker{
ok

2022-07-29 02:24 UTC, YusongWang commented on sources/TokenLocker.move
> +    struct TokenLocker<phantom T:store> has store,key{
ok.换成LockerContainer了

2022-07-29 02:25 UTC, YusongWang commented on sources/TokenLocker.move
> +    struct TokenLocker<phantom T:store> has store,key{
感谢提醒

2022-07-29 02:25 UTC, YusongWang commented on sources/TokenLocker.move
> +    const LOCK_TIME_PASSD:u64= 2;
已经格式化了,非常感谢。

2022-07-29 02:27 UTC, YusongWang commented
> 
I need some help, i can't hold any Token<TokenType> in my testcase function.  
Would you like share some template for test  pls, Thankyou.

2022-07-29 03:05 UTC, WGB5445 commented
> > 
> 
> I need some help, i can't hold any Token in my testcase function. Would you like share some template for test pls, Thankyou.

You can use this case to test your code, but you still need to add some other case tests
You can use STC as a test Token, the effect is similar to using MyToken, but more convenient
```
//# init -n test --public-keys 

//# faucet --addr creator --amount 100000000000

//# faucet --addr alice --amount 100000000000

//# publish
module creator::MockToken {
    use StarcoinFramework::Token;
    use StarcoinFramework::Account;

    struct MyToken has copy, drop, store { }

    public fun init(account: &signer) {
        Token::register_token<MyToken>(account, 3);
        Account::do_accept_token<MyToken>(account);
    }

    public fun mint(account: &signer, to:address, amount: u128) {
        let token = Token::mint<MyToken>(account, amount);
        Account::deposit<MyToken>(to, token);
    }
}

//# run --signers creator
script {
    use creator::MockToken;

    fun init(sender: signer) {
        MockToken::init(&sender);
    }
}
// check: EXECUTED

//# run --signers creator
script {
    use creator::MockToken;
    use StarcoinFramework::Account;
    fun send(sender: signer) {
        MockToken::mint(&sender, @alice, 100000);
        let balance = Account::balance<MockToken::MyToken>(@alice);
        assert!(balance == 100000 ,1001);
    }
}
// check: EXECUTED

//# block --author 0x1 --timestamp 8640000

//# run --signers alice
script {
    use creator::MockToken::{Self, MyToken};
    use StarcoinFramework::Account;
    use SFC::TokenLocker;
    fun lock(sender: signer) {
        TokenLocker::lock_self<MyToken>(&sender, 100000, 9000000);
        let balance = Account::balance<MockToken::MyToken>(@alice);
        assert!(balance == 0 ,1001);
    }
}
// check: EXECUTED

//# block --author 0x1 --timestamp 9000000

//# run --signers alice
script {
    use creator::MockToken::{Self, MyToken};
    use StarcoinFramework::Account;
    use SFC::TokenLocker;
    fun lock(sender: signer) {
        TokenLocker::unlock_self<MyToken>(&sender);
        let balance = Account::balance<MockToken::MyToken>(@alice);
        assert!(balance == 100000 ,1001);
    }
}
// check: EXECUTED
```

2022-07-29 03:12 UTC, WGB5445 commented on sources/TokenLocker.move
> +    const LOCK_TIME_PASSD: u64 = 2;
这里的错误处理应该用 ERR_LOCK_TIME_XXX 等
错误代码 可以从 101开头，与标准库保持一致
可以考虑 使用标准库中的 Errors 库处理

2022-07-29 03:12 UTC, WGB5445 commented on sources/TokenLocker.move
> +        assert!(unlock_time > Timestamp::now_milliseconds(), LOCK_TIME_PASSD);
这里使用毫秒作为单位感觉不是很必要，因为区块间隔大概在 5 秒左右，使用毫秒作为区分有些太细了

2022-07-29 03:12 UTC, WGB5445 commented on sources/TokenLocker.move
> +    public fun lock_self<TokenT: store>(sender: &signer, amount: u128, unlock_time: u64) acquires LockerContainer {
可以增加 script  关键字，方便任意用户调用

2022-07-29 03:12 UTC, WGB5445 commented on sources/TokenLocker.move
> +    public fun unlock_self<TokenT: store>(sender: &signer) acquires LockerContainer {
同上 增加 script 关键字

2022-07-29 04:54 UTC, YusongWang commented on sources/TokenLocker.move
> +    const LOCK_TIME_PASSD: u64 = 2;
ok

2022-07-29 04:55 UTC, YusongWang commented on sources/TokenLocker.move
> +        assert!(unlock_time > Timestamp::now_milliseconds(), LOCK_TIME_PASSD);
改成秒了

2022-07-29 04:55 UTC, YusongWang commented on sources/TokenLocker.move
> +    public fun lock_self<TokenT: store>(sender: &signer, amount: u128, unlock_time: u64) acquires LockerContainer {
增加了

2022-07-29 04:55 UTC, YusongWang commented on sources/TokenLocker.move
> +    public fun unlock_self<TokenT: store>(sender: &signer) acquires LockerContainer {
增加了

2022-07-29 05:15 UTC, 0xpause commented on integration-tests/token_locker_test.move
> +// check: EXECUTED
这里注释写错了吧，应该是 abort ?

2022-07-29 05:38 UTC, YusongWang commented on integration-tests/token_locker_test.move
> +// check: EXECUTED
是的。这里应该是确认 没有锁定token.调用解锁函数不会出错。balance ==100000 才对。我处理一下。

2022-07-29 05:47 UTC, 0xpause approved these changes

2022-07-29 06:01 UTC, WGB5445 approved these changes

2022-07-29 07:18 UTC, merged