add TimerHelper
starcoinorg/starcoin-framework-commons pull request #45
Opened 2022-07-29 07:33 UTC by YusongWang

## Pull request type
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #31 

## What is the new behavior?

## Other information

2022-07-29 10:05 UTC, WGB5445 commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
我觉得默认应该是秒
把毫秒函数改为 add_days_for_millieseconds

2022-07-29 10:11 UTC, YusongWang commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
好的，我修改一下。

2022-07-29 13:05 UTC, 0xpause requested changes

2022-07-29 13:05 UTC, 0xpause commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
不用 add 吧， 直接返回  days 的秒数。

2022-07-29 13:17 UTC, YusongWang commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
public fun days(days: u64): u64 {} 像这样吗？ 可能不是太灵活,虽然方便。

2022-07-29 13:49 UTC, 0xpause commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
你说的灵活是指? 不应该更灵活吗？

2022-07-29 13:56 UTC, YusongWang commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
哦，我理解你的意思了。你是说只返回多少天的时间戳，1天的就是1*60*60*24。我理解的是前一个值加上当前时间戳。

你说的做法:
    public fun days(days: u64): u64 {
        DAY_IN_SECONDS * days
    }

我理解的做法:
    public fun days(days: u64): u64 {
        add(Timestamp::now_seconds(), DAY_IN_SECONDS * days)
    }

你说的是上面那种做法吗？如果是的话，和我目前的做法差不多。只不过一个是传参近来，一个是用户自己相加。

2022-07-29 15:46 UTC, 0xpause commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
是的，第一种。TimeHelper 作为一个辅助方法，不应该涉及具体的业务逻辑。用户也可能做减法吧。

2022-07-29 15:48 UTC, 0xpause commented
测试没必要写集成测试了，写个单元测试就可以了。

2022-07-29 22:19 UTC, YusongWang commented
> 测试没必要写集成测试了，写个单元测试就可以了。

好

2022-07-29 22:20 UTC, YusongWang commented on sources/TimeHelper.move
> +    public fun add_days(timestamp: u64, days: u64): u64 {
> 是的，第一种。TimeHelper 作为一个辅助方法，不应该涉及具体的业务逻辑。用户也可能做减法吧。

有道理

2022-07-30 03:32 UTC, 0xpause approved these changes

2022-07-31 02:06 UTC, WGB5445 approved these changes

2022-07-31 03:39 UTC, merged