feat: add Escrow
starcoinorg/starcoin-framework-commons pull request #47
Opened 2022-08-03 04:24 UTC by qiwihui

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Basic escrow module: holds an object designated for a recipient until the sender approves withdrawal. it contains:
- `escrow`: Stores the sent object in an escrow object.
- `transfer`: Transfers escrowed object to the recipient.
- `accept`: Accepts the escrowed object.

Issue Number: #28 

## What is the new behavior?

-
-
-

## Other information

2022-08-03 05:48 UTC, jiangying000 commented
maybe add some tests?

2022-08-03 06:24 UTC, qiwihui commented
sure, working on tests

2022-08-03 09:56 UTC, uvd commented on sources/Escrow.move
> +    public entry fun escrow<T: key + store>(sender: &signer, recipient: address, obj_in: T) {
我们的move 版本现在支持 entry 关键字了么 @jolestar

2022-08-03 16:32 UTC, jolestar commented on sources/Escrow.move
> +    public entry fun escrow<T: key + store>(sender: &signer, recipient: address, obj_in: T) {
还没支持，先用 public(script)

2022-08-03 16:39 UTC, jolestar approved these changes

2022-08-03 16:39 UTC, jolestar commented on sources/Escrow.move
> +    public entry fun escrow<T: key + store>(sender: &signer, recipient: address, obj_in: T) {
需要同时提供两个方法，一个是供其他 module 调用的，sender 为 `&signer`，另外一个是 entry 入口方法，现在只能用 `pubic(script)` 定义， sender 需要是 `signer`。如果为了避免命名冲突，方法名后可以加上 `entry`. 比如 `public(script) fun escrow_entry(sender:singer, recipient: address, obj_in: T)` 这样.

2022-08-03 16:39 UTC, jolestar commented on sources/Escrow.move
> +    struct Escrow<T: key + store> has key {
这里的 T 不需要 `key` ability

2022-08-03 16:41 UTC, jolestar requested changes
前面误操作

2022-08-04 06:26 UTC, qiwihui commented
@jolestar pls help to review this PR

2022-08-04 08:44 UTC, jolestar commented on sources/Escrow.move
> +    public fun get_recipient<T: store+copy>(sender: address): address acquires Escrow {
这里不需要限制 T 需要 `copy`,

2022-08-04 08:44 UTC, jolestar commented on sources/Escrow.move
> +    public fun get_obj<T: store+copy>(sender: address): Option<T> acquires Escrow {
感觉大多数需要通过 `escrow` 托管的 object，都不应该是可以 `copy` 的，可以 `copy` 的物品就没必要托管。所以感觉这个方法没啥用。

2022-08-04 08:44 UTC, jolestar commented on sources/Escrow.move
> +        exists<Escrow<T>>(account)
是不是应该同时检查 obj 是否为 None

2022-08-04 10:08 UTC, qiwihui commented on sources/Escrow.move
> +    public fun get_obj<T: store+copy>(sender: address): Option<T> acquires Escrow {
嗯是的，这个原本是想用于测试，但对于这个模块显得多余

2022-08-04 10:09 UTC, qiwihui commented on sources/Escrow.move
> +        exists<Escrow<T>>(account)
嗯需要

2022-08-04 10:11 UTC, qiwihui commented on sources/Escrow.move
> +        exists<Escrow<T>>(account)
```rust
    public fun contains<T: store>(account: address): bool acquires Escrow {
        if (exists<Escrow<T>>(account) == false) return false;
        let escrow = borrow_global<Escrow<T>>(account);
        Option::is_some(&escrow.obj)
    }
```

2022-08-04 10:19 UTC, jolestar commented
实现没问题了，不过有个机制上的安全问题。

如果 recipient 不 accept， sender 是不是也永远无法 transfer，也无法取出 escrow 的 object。

2022-08-04 10:22 UTC, qiwihui commented
Starcoin 能让 recipient 去做类似于 withdraw 这样的操作吗？但是这样就没办法删除 sender 那边的object了

2022-08-04 10:35 UTC, jolestar commented on sources/Escrow.move
> +    public fun transfer<T: store>(sender: &signer) acquires Escrow {
如果 transfer 了，recipient 好像也无法从 Escrow 中取出来。感觉机制上需要考虑一下。

2022-08-04 10:35 UTC, jolestar commented on sources/Escrow.move
> +    }
感觉是不是应该换个思路，比如 escrow 只返回 Escrow 对象，而不关心 Escrow 保存在哪里？在 Escrow 基础上再封装 TokenEscrow 等 module，处理具体的类型。 比如 Token 需要拿出来后 deposit 到 Account Balance 中。 @0xpause @jiangying000 @uvd 觉得呢

2022-08-04 12:33 UTC, 0xpause requested changes
处理 Token 对象，一定要严谨，做好边界检查。

2022-08-04 12:33 UTC, 0xpause commented on sources/Escrow.move
> +    }
我觉得两种方式都可以提供。
1. 如果支持 T 为任意资源对象，那其实该库不知道如何处理 T 的，这就需要传出去有合约开发者自己决定如何处理；
2. 更常见的就是保存 Token，这个其实就是 token 的 deposit 和 withdraw，那这个库就可以把这个工作做了，提供一个 script 接口，用户可以直接用的。

对于第2中情况，需要增加一个状态，表示 recipient 是否可以提取，这个状态由 sender 来设置。Escrow 一个主要目的就是表示 Token 已经给到 recipient 了，但是需要满足给定的条件后，才能提取。如果没有条件，那直接 transfer token 就好了，不需要这个 Escrow。

@qiwihui 第2种情况，就是 @jolestar 所说的把 Token 拿出来， deposit 到 receipt 的 Balance 中。现在这个实现，receipt 拿到 Escrow 是没啥作用的，也无法提取 Escrow 里面的 obj（除非再增加一个提取的接口）

2022-08-04 12:33 UTC, 0xpause commented on integration-tests/escrow_test.move
> +// check: EXECUTED
建议增加一些不正常使用的测试用例，多人使用的测试用例。

2022-08-04 12:33 UTC, 0xpause commented on sources/Escrow.move
> +    struct Escrow<T: store> has key {
这样的 struct 无法满足多个 Escrow 的情况把。 比如 sender 给 receipt1 和 receipt2 分别准备 escrow，会怎么样？可以参考下 TokenLocker 和 Vesting 里面的实现。

2022-08-04 12:33 UTC, 0xpause commented on sources/Escrow.move
> +        move_to(sender, escrow);
增加边界检查，加入 sender 名下已经有 escrow 了会怎样。

2022-08-04 12:33 UTC, 0xpause commented on sources/Escrow.move
> +        let obj_in = Option::destroy_some(obj);
recipient 名下一定有 Escrow 对象吗？ 如果 t_escrow.obj 有值要怎样处理？

2022-08-04 12:38 UTC, jiangying000 commented on sources/Escrow.move
> +    public fun accept<T: store>(recipient: &signer) {
accept 的时候 recipient 的resource的 T 的余额是否要加一下

2022-08-04 12:38 UTC, jiangying000 commented on sources/Escrow.move
> +    public fun accept<T: store>(recipient: &signer) {
可能要先判断下：if (exists<Escrow<T>>(address))

2022-08-05 03:57 UTC, qiwihui commented on sources/Escrow.move
> +    }
这块我理解这么设计：

增加一个Contaier来存放多个 Escrow
```Move
    struct Escrow<T: store> has store {
        recipient: address,
        obj: T,
    }

    struct EscrowContainer<T: store> has key {
        escrows: vector<Escrow<T>>
    }
```

提供以下的函数进行操作：

- `public fun escrow<T: store>(sender: &signer, recipient: address, obj_in: T)`
    - 将对象存储在EscrowContainer中
- `public fun transfer<T: store>(sender: &signer, recipient: address): vector<T>`
    - 取出满足recipient的Escrow对象，并将其存储在vector中
- `public fun contains<T: store>(sender: address, recipient: address): bool`
    - 查看EscrowContainer中是否存在满足recipient的Escrow对象

- `public(script) fun deposit_entry<TokenType: store>(sender: signer, amount: u128, recipient: address)`
    - 将Token存储在EscrowContainer中
- `public(script) fun transfer_entry<TokenType: store>(sender: signer, recipient: address)`
    - 将EscrowContainer中的Token取出，并用 Account::deposit 转移给recipient

starcoin 的账户模型我感觉限制了 EscrowContainer 中满足条件的Escrow 对象的删除，所以不知道 recipient 怎么进行提取，只能通过 sender 来 transfer，请问这块要怎么处理？

2022-08-05 03:59 UTC, qiwihui commented
这块我想这么设计：

增加一个 EscrowContainer 来存放多个 Escrow：

```Move
    struct Escrow<T: store> has store {
        recipient: address,
        obj: T,
    }

    struct EscrowContainer<T: store> has key {
        escrows: vector<Escrow<T>>
    }
```

提供以下的函数进行操作：

- `public fun escrow<T: store>(sender: &signer, recipient: address, obj_in: T)`
    - 将对象存储在EscrowContainer中
- `public fun transfer<T: store>(sender: &signer, recipient: address): vector<T>`
    - 取出满足recipient的Escrow对象，并将其存储在vector中
- `public fun contains<T: store>(sender: address, recipient: address): bool`
    - 查看EscrowContainer中是否存在满足recipient的Escrow对象

- `public(script) fun deposit_entry<TokenType: store>(sender: signer, amount: u128, recipient: address)`
    - 将Token存储在EscrowContainer中
- `public(script) fun transfer_entry<TokenType: store>(sender: signer, recipient: address)`
    - 将EscrowContainer中的Token取出，并用 Account::deposit 转移给recipient

starcoin 的账户模型只能操作账户下的 EscrowContainer 中满足条件的Escrow 对象的删除，所以不知道 recipient 怎么进行提取的同时删除原来账户的对象，只能通过 sender 来 transfer，请问这块要怎么处理？

2022-08-05 06:53 UTC, jolestar commented
>   * 将对象存储在EscrowContainer中
> * `public fun transfer<T: store>(sender: &signer, recipient: address): vector<T>`

这个方法的调用者是 sender，如果拿出来后，vector<T> 存哪里也是个问题。感觉这个应该是由 recipient 来领取比较合适？



> * `public(script) fun deposit_entry<TokenType: store>(sender: signer, amount: u128, recipient: address)`
>   
>   * 将Token存储在EscrowContainer中
> * `public(script) fun transfer_entry<TokenType: store>(sender: signer, recipient: address)`
>   
>   * 将EscrowContainer中的Token取出，并用 Account::deposit 转移给recipient
> 

Token 相关的操作感觉可以放在另外一个 module 里，比如 TokenEscrow，TokenEscow 依赖 Escow，进行了二次封装。比如可能以后还可以有 NFTEscrow 等。

这个 module 感觉和 StarcoinFramework 中的 Offer 挺像的，感觉可以借鉴一下。

2022-08-06 17:02 UTC, qiwihui commented
@jolestar 我提交了一些修改，请帮忙review一下

2022-08-07 10:38 UTC, 0xpause commented
需要一个 approval 或者设置 claimable 状态的接口吧，不然 sender 添加 Escrow 后 receipt 就可以 claim 了，没啥意义吧。 @jiangying000 @jolestar @uvd 你们觉得呢？

2022-08-07 14:49 UTC, jolestar commented
> 需要一个 approval 或者设置 claimable 状态的接口吧，不然 sender 添加 Escrow 后 receipt 就可以 claim 了，没啥意义吧。 @jiangying000 @jolestar @uvd 你们觉得呢？

我也在想这个 `Escrow` 的使用场景，如果没有条件的话，感觉就和 `Offer` 差不多了。

感觉是不是应该有个 `claimable` 的状态，由 sender 设置，但如果 sender 不设置，默认超过 x 时间后就可以自动 claimable。但如果可以 claimable 后，又超过 x 时间，recipient 没有来领取，sender 可以收回。

2022-08-07 14:53 UTC, jolestar commented on sources/TokenEscrow.move
> +    public fun withdraw<TokenType: store>(account: &signer, sender: address) {
withdraw 是要拿东西出来。这个实际上是 transfer。

2022-08-07 14:53 UTC, jolestar commented on sources/TokenEscrow.move
> +    public(script) fun deposit_to_entry<TokenType: store>(sender: signer, amount: u128, recipient: address) {
要不保持一致 `deposit` 和 `deposit_entry`

2022-08-08 01:56 UTC, qiwihui commented on sources/TokenEscrow.move
> +    public fun withdraw<TokenType: store>(account: &signer, sender: address) {
嗯，withdraw和transfer语义不一样，这里是应该用 transfer

2022-08-08 03:47 UTC, jiangying000 commented
发现movemate sui里有两个escrow实现，可能可以参考下
https://github.com/pentagonxyz/movemate/blob/d8a4c28890e228c282ad43a9d9065a64007a48a2/sui/sources/escrow_shared.move
https://github.com/pentagonxyz/movemate/blob/d8a4c28890e228c282ad43a9d9065a64007a48a2/sui/sources/escrow.move

2022-08-08 07:08 UTC, qiwihui commented
目前这边的实现也是参考这两个实现，再加上大家的讨论实现的

2022-08-08 07:10 UTC, qiwihui commented
> > 需要一个 approval 或者设置 claimable 状态的接口吧，不然 sender 添加 Escrow 后 receipt 就可以 claim 了，没啥意义吧。 @jiangying000 @jolestar @uvd 你们觉得呢？
> 
> 
> 
> 我也在想这个 `Escrow` 的使用场景，如果没有条件的话，感觉就和 `Offer` 差不多了。
> 
> 
> 
> 感觉是不是应该有个 `claimable` 的状态，由 sender 设置，但如果 sender 不设置，默认超过 x 时间后就可以自动 claimable。但如果可以 claimable 后，又超过 x 时间，recipient 没有来领取，sender 可以收回。 

这个是针对每一个接收者地址设置claimable和时间吧？

2022-08-08 09:25 UTC, 0xpause commented
> 



> > > 需要一个 approval 或者设置 claimable 状态的接口吧，不然 sender 添加 Escrow 后 receipt 就可以 claim 了，没啥意义吧。 @jiangying000 @jolestar @uvd 你们觉得呢？
> > 
> > 
> > 我也在想这个 `Escrow` 的使用场景，如果没有条件的话，感觉就和 `Offer` 差不多了。
> > 感觉是不是应该有个 `claimable` 的状态，由 sender 设置，但如果 sender 不设置，默认超过 x 时间后就可以自动 claimable。但如果可以 claimable 后，又超过 x 时间，recipient 没有来领取，sender 可以收回。
> 
> 这个是针对每一个接收者地址设置claimable和时间吧？

应该是每一个 escrow 对象

2022-08-09 06:46 UTC, qiwihui commented
Escrow 的基本功能是不是应该是把一个 object 存入 sender 账户，然后等 approve 之后 recipient 就可以获取，一种方式是通过 sender 进行 transfer，正如 https://github.com/pentagonxyz/movemate/blob/main/sui/sources/escrow.move 库中实现的一样，或者通过设置 claimable 等着 recipient 进行 claim，正如这边的实现。至于是什么时间获取，到时间之后是否退回，正如 @jiangying000 所说，可以作为辅助组合加入，组合成 TimedEscrow 等模块。 @jolestar

2022-08-09 06:57 UTC, jolestar commented
组合的方式感觉挺好，也符合 Move 的设计模式。

2022-08-09 06:58 UTC, jolestar approved these changes
组合式的玩法可以后面在设计

2022-08-09 08:00 UTC, 0xpause requested changes

2022-08-09 08:00 UTC, 0xpause commented on sources/Escrow.move
> +            if (index < escrow_len) {
这里建议用 asser 报告 index 非法时的错误。现在 index 如果有错误问题就被隐藏了。

2022-08-09 08:53 UTC, 0xpause approved these changes

2022-08-09 09:43 UTC, jiangying000 approved these changes

2022-08-09 09:43 UTC, jiangying000 commented on sources/Escrow.move
> +    public fun set_claimable<T: store>(sender: &signer, index: u64) acquires EscrowContainer {
调用时这个index怎么获取？

2022-08-09 09:43 UTC, jiangying000 commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
调用者有方便的方式获取这个 index 吗？

2022-08-09 09:55 UTC, qiwihui commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
目前看没有函数支持读取所有的escrow对象。我觉得可以加一个 get 函数，获取对应的escrows对象，提供 index 指引，同时这个get函数可以过滤 recipient，如何？

2022-08-09 10:17 UTC, jiangying000 commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
好的

2022-08-10 08:05 UTC, qiwihui commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
这个功能的思路实现有些问题无法解决，一则 Move 不支持 vector<&T> 包含 reference 的返回，另一个是 Escrow 内保存的 obj 只支持 store 能力，无法在不删除的情况下获取内容。思路代码大概是这样的：

```rust
    public fun get<T: store>(container: &vector<T>): vector<T> {
        let items = Vector::empty<T>();
        if (!Vector::is_empty<T>(container)) {
            let container_len = Vector::length<T>(container);
            let i = 0;
            while (i < container_len) {
                let item = Vector::borrow(container, i);
                Vector::push_back<T>(&mut items, item);
                i = i + 1;
            }
        };
        items
    }
```

请问这块你们有什么思路吗？

2022-08-10 08:50 UTC, jolestar commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
NFTGallary 那边的思路是 定义一个 NFTInfo 的可以 `copy，drop` 的 Info struct,这样可以支持获取 resource struct 对应的 Info，但不用挪出来。还有个办法是允许 sender 拿出 EscrowContainer，然后 borrow mut Escrow，这样就可以通过 `&mut Escrow` 来修改 Escrow 的属性。

2022-08-12 02:38 UTC, qiwihui commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
我的理解是 NFTInfo 结构中所包含的数据（Metadata，NFTMeta）都会有 copy 能力，这边因为没有 copy 能力所以没法实现。后面那个允许 sender 拿出 EscrowContainer 我也没太懂，是指通过 `&mut Escrow` 修改其中的属性，比如增加一个索引 `index: Option<u64>` 属性，然后在添加删除的过程中维护这个索引。

2022-08-12 10:09 UTC, jolestar commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
如果 Escrow 没有一个 id 类的标志，找个 index 就只能是开发者在链下去计算好，然后使用了。

2022-08-23 11:58 UTC, 0xpause commented on sources/TokenEscrow.move
> +    public fun set_claimable<TokenType: store>(sender: &signer, index: u64) {
这个合约时给开发者用的，我觉得开发者记录 index 是可行，无论是链上还是链下。就算是 id 类的标志或者其他标志，都是需要记录或者计算的。

可以增加一个 EscrowInfo 类和查询接口，用来获取所有的 Escrow 信息，供开发者判断某个 escrow 是否可以 claimable。

2022-08-24 05:10 UTC, merged