add ASCII split function
starcoinorg/starcoin-framework-commons pull request #52
Opened 2022-08-22 15:11 UTC by tiankonglan

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
no code

Issue Number: N/A

## What is the new behavior?

add ASCII split fuction
-
-

## Other information

2022-08-23 08:38 UTC, jiangying000 requested changes

2022-08-23 08:38 UTC, jiangying000 commented on sources/ASCII.move
> +      };
调用 split(string(b"a878"), char(56))

返回的是：['a','7']
一般语言对这种case返回：['a','7','']

2022-08-23 08:38 UTC, jiangying000 commented on sources/ASCII.move
> +   public fun split(string: String, char: Char) :  vector<String> {
缩进少了个空格

2022-08-23 08:38 UTC, jiangying000 commented on integration-tests/ascii_test.move
> +//split string by char,  3th scence
scence -> scene ?

2022-08-23 08:39 UTC, jiangying000 commented on integration-tests/ascii_test.move
> +            let result = ASCII::split(string,  ASCII::char(95u8)); // _ ansci is 95
```suggestion
            let result = ASCII::split(string,  ASCII::char(95u8)); // _ ascii is 95
```

2022-08-23 11:22 UTC, WGB5445 commented
在代码完成后，可以用 `idea` 上的插件 格式化一下，统一下规范

2022-08-25 03:13 UTC, WGB5445 approved these changes

2022-08-25 12:43 UTC, jiangying000 commented on sources/ASCII.move
> +                if (i == len - 1) {  // special
如果 i == 0 呢

2022-08-25 15:55 UTC, jiangying000 commented on sources/ASCII.move
> +                if (i == len - 1) {  // special
哦，我搞错了

2022-08-29 01:13 UTC, merged